[package]
name = "modu"
version = "0.6.0"
edition = "2021"
repository = "https://github.com/cyteon/modu"
homepage = "https://modu.cyteon.dev"
description = "A fast and simple interpreted language"
documentation = "https://modu.cyteon.dev/docs/quickstart"
license = "MIT"
authors = ["Cyteon"]
keywords = ["programming-language", "cli", "interpreter", "language"]
exclude = ["/examples", "/tmp"]

[dependencies]
bat = "0.24.0"
chrono = "0.4.39"
libloading = "0.8.6"
logos = "0.15.0"
rand = "0.8.5"
reqwest = { version = "0.12.11", features = ["blocking", "json"] }
rouille = "3.6.2"
serde_json = "1.0.134"
toml = "0.8.19"
zip = "2.2.2"
openssl = { version = "0.10", features = ["vendored"] }
uuid = { version = "1.13.1", features = ["v4"]}
